import type { Metadata } from "next";
import "./css/reset.css"
import "./css/fonts.css";
import "./css/globals.css";
import "./css/style.css";
import { CopyButton } from "./component/client/Button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
    >
      <body 
        suppressHydrationWarning={true}
      >
        {children}

        <footer className="footer-area small color-lowlight">
          <p className="footer-mail">
            <CopyButton
              email="sungsu0221@naver.com"
            />

          </p>
          <p className="copyright">
            © 2026. <span className="font-bold">Choi Seong-su</span>. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
